Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,10 +29,11 @@ jobs:
           #javac -d out -sourcepath src panels/src/main/java/com/izforge/izpack/panels/mypanels/*.java
 
       # Step 4: Install IzPack compiler
-      - name: Download IzPack Standalone Compiler
+      - name: Download IzPack Compiler
         run: |
-          curl -L -o izpack-compiler.jar \
+          curl -L -f -o izpack-compiler.jar \
           https://repo1.maven.org/maven2/org/izpack/izpack-standalone-compiler/5.2.3/izpack-standalone-compiler-5.2.3.jar
+          file izpack-compiler.jar   test $(stat -c%s izpack-compiler.jar) -gt 4000000 || (echo "Download incomplete or invalid JAR"; exit 1)
 
       - name: Build Installer
         run: |
